#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-pedrolumbi-dccrtaller-v0ohs6wezbj.ws-us106.gitpod.io
- 8025-pedrolumbi-dccrtaller-v0ohs6wezbj.ws-us106.gitpod.io
- 8036-pedrolumbi-dccrtaller-v0ohs6wezbj.ws-us106.gitpod.io
